"""create portfolios and holdings

Revision ID: d69d1ac60643
Revises:
Create Date: 2026-08-25 23:46:23.281656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d69d1ac60643"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolios",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("benchmark_ticker", sa.String(length=16), nullable=False),
        sa.Column("mandate_constraints", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolios_tenant_id"), "portfolios", ["tenant_id"], unique=False)
    op.create_index("ix_portfolios_tenant_id_id", "portfolios", ["tenant_id", "id"], unique=False)
    op.create_table(
        "holdings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "portfolio_id", "ticker", "as_of", name="uq_holdings_portfolio_ticker_as_of"
        ),
    )
    op.create_index(
        "ix_holdings_portfolio_id_ticker", "holdings", ["portfolio_id", "ticker"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_holdings_portfolio_id_ticker", table_name="holdings")
    op.drop_table("holdings")
    op.drop_index("ix_portfolios_tenant_id_id", table_name="portfolios")
    op.drop_index(op.f("ix_portfolios_tenant_id"), table_name="portfolios")
    op.drop_table("portfolios")
    # ### end Alembic commands ###
